# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["kinematic_scattering.py"]

doc_url = "https://gduscher.github.io/pyTEMlib_nbdev/"

git_url = "https://github.com/gduscher/pyTEMlib_nbdev/tree/master/"

def custom_doc_links(name): return None
